[package]
name = "defcon"
version = "0.1.0"
authors = ["Antoine POPINEAU <antoine@popineau.eu>"]
edition = "2018"

default-run = "defcon"

[[bin]]
name = "defcon"
path = "src/bin/controller/main.rs"

[[bin]]
name = "defcon-runner"
path = "src/bin/runner/main.rs"

[dependencies]
anyhow = "^1.0"
async-trait = "0.1"
base64 = "0.13"
capabilities = "0.3"
chrono = { version = "0.4", default_features = false, features = [] }
dns-lookup = "^1.0"
extend = "1.0"
futures = "0.3"
humantime = "^2.1"
jsonwebtoken = "7.2"
kvlogger = { version = "0.5", features = ["datetime"] }
lazy_static = "1.4"
log = "*"
rand = "0.8"
refinery = { version = "0.5", features = ["mysql"] }
regex = "1.0"
reqwest = { version = "0.11", features = ["json"] }
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "2a493683135ebcc34df34a4ed1eea532fac1895f" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", rev = "2a493683135ebcc34df34a4ed1eea532fac1895f", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
sha2 = "0.9"
slack-hook = "0.8"
sqlx = { version = "0.5", default_features = false, features = ["macros", "mysql", "runtime-tokio-rustls", "chrono", "all-types"] }
ssl-expiration2 = "0.2"
surge-ping = "0.1"
thiserror = "^1.0"
tokio = { version = "1.0", default_features = false, features = ["time", "net"] }
trust-dns-client = { version = "0.20", default_features = false }
uuid = { version = "0.8", features = ["v4"] }
whois2 = "0.0.1"

[dev-dependencies]
serial_test = "0.5"
url = "^2.2"
