[package]
name = "defcon"
version = "0.1.0"
authors = ["Antoine POPINEAU <antoine@popineau.eu>"]
edition = "2018"

[dependencies]
anyhow = "^1.0"
async-trait = "0.1"
base64 = "0.13"
capabilities = "0.3"
chrono = "0.4"
dns-lookup = "^1.0"
ekko = "0.2"
futures = "0.3"
kvlogger = { version = "0.4", features = ["datetime"] }
log = "*"
parse_duration = "^2.1"
rand = "0.8"
refinery = { version = "0.5", features = ["mysql"] }
reqwest = { version = "0.11", features = ["json"] }
rocket = { git = "https://github.com/SergioBenitez/Rocket" }
rocket_contrib = { git = "https://github.com/SergioBenitez/Rocket", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
sha2 = "0.9"
slack-hook = "0.8"
sqlx = { version = "0.4", features = ["mysql", "runtime-tokio-rustls", "chrono", "all-types"] }
ssl-expiration = "0.1"
thiserror = "^1.0"
tokio = { version = "0.2", features = ["time", "net"] }
trust-dns-client = { version = "0.20", default-features = false }
uuid = { version = "0.8", features = ["v4"] }
whois2 = "0.0.1"
