CREATE TABLE groups (
  `id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `uuid` CHAR(37) NOT NULL UNIQUE,
  `name` VARCHAR(255) NOT NULL
);

ALTER TABLE checks
ADD `group_id` BIGINT UNSIGNED AFTER `uuid`;

ALTER TABLE checks
ADD CONSTRAINT fk_check_group FOREIGN KEY (group_id) REFERENCES groups (id)
ON DELETE SET NULL;
